### PR TITLE
Make download script working on mac

### PR DESCRIPTION
**Pull request by jrichter1**
Reflecting the changed folder structure of Eclipse on Mac.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Looks good to me. @psrna @nickboldt Do you want to have a look?

**Comment by psrna** [comment]
@mickaelistria how do we use install-grinder if we do 8.1 maintenance - from branch - or specific version?  Since this probably won't work on luna where eclipse dir is called 'eclipse' and not 'Eclipse.app'

**Comment by mickaelistria** [comment]
We can do whatever we want, but it's indeed better if we can use a single version. So @jrichter1 , can you try to have it also work for previous Mac layout? I guess we can delete both eclipse/ and eclipse.app/ directories when needed and then check what directory was created instead of deducing it from OS ?

**Comment by jrichter1** [comment]
Fair enough, I'll get to it.

**Comment by jrichter1** [comment]
So, what do you think about the updated version? Should run on both versions.

**Comment by mickaelistria** [comment]
This seems good to me. @psrna WDYT?

**Comment by psrna** [comment]
Looks good to me too.

**Comment by mickaelistria** [comment]
PR was merged and CI job is done. So latest snapshot of install-grinder should contain the suggested patch. Thanks!

**Pull request merged**
