### PR TITLE
Ignore eclipse files

### PR DESCRIPTION
**Pull request by apodhrad**
We don't need these files in git repository

### CODE REVIEW

**Comment by mickaelistria** [comment]
What's the benefit in removing them?

**Comment by apodhrad** [comment]
After importing the project into my Eclipse/JBDS some of the files (such as .classpath, .project) are changed. Then, by doing diff I see these changes => less readable diff

**Comment by mickaelistria** [comment]
What I don't understand are why such files are changed? Is it m2e that doesn't detect that .project and .classpath file already exists?
@fbricon  any idea?

**Comment by apodhrad** [comment]
I'm not sure :( I just removed these files from all repositories I use.
Moreover, we don't need these files, so why to keep them in the repo?

**Comment by mickaelistria** [comment]
We use them so that someone can use "Import existing project into workspace" wizard, and will get the project fully configured.

**Comment by maxandersen** [comment]
@apodhrad in past we kept .project/.classpath so we could import/work with the projects without using 
m2e.

If you are seeing differences from .project in git and remotely then something *has* changed which should be updated in git anyway.

Some projects started remove them and it is rather problematic since m2e is not capable of handling *all* jbosstools projects effectively.

I still recommend keeping them in git to allow for easier and faster import and project builds. I'm though not insisting these days since it is for some projects necessary to use m2e to import to have the libraries they need from mvn copied to the lib directory.

**Comment by apodhrad** [comment]
@maxandersen thanks for your explaining, that makes sense. I usually import all maven projects as Existing Maven Project, maybe this way of importing makes the changes.

So, if you want to keep such files in the repo, I'm ok with it and you can close this issue.

**Comment by maxandersen** [comment]
closing it.

p.s. doing a commit that make the result be as what the maven import result in and that is stable (and working) would be fine.

**Pull request closed without merging**
